# Generated by Django 2.2 on 2019-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_photos/')),
                ('likes', models.IntegerField(default=0)),
                ('taken_date', models.DateField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
